CREATE table sensor (
    id int primary key generated by default as identity,
    name varchar(100) not null
);
CREATE Table measurements(
    id int primary key generated by default as identity,
    value double precision not null ,
    raining boolean not null ,
    date timestamp not null,
    sensor_id int references sensor(id) not null
);

